apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::471593880163:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1N4ZQDSB60RUY
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::471593880163:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-09T19:32:35Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1553"
  uid: a29b9e4e-5b84-40db-b24a-a70523d381fd
