apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::471593880163:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-19OPOGT5ILUL5
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::471593880163:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-10T12:51:42Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1584"
  uid: 3b5e80a3-7457-4e2c-ab7b-db6ef1087a3b
